
version: "3"

services: 
    flask-app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: dcn558/iss_tracker:project
        volumes:
            - ./config.yaml:/config.yaml




